variables:
- group: bicep-network-lab

trigger:
- none

stages:
  - stage: 'NetworkLabWhatIf'
    dependsOn: []
    displayName: Network Lab What If

    jobs:
      - job: 'NetworkLabWhafIfJob'
        displayName: 'Conduct What-If deployment check of resources'
        pool:
          vmImage: 'windows-latest'

        steps:

          - task: replacetokens@5
            inputs:
              rootDirectory: '$(System.DefaultWorkingDirectory)/modules/networking/'
              targetFiles: '**/*.bicepparam'
              encoding: 'auto'
              tokenPattern: 'default'
              writeBOM: true
              actionOnMissing: 'warn'
              enableTelemetry: false

          - task: AzurePowerShell@5
            displayName: 'Azure Powershell What-If task'
            inputs:
              azureSubscription: $(azureSubscription)
              ScriptType: InlineScript
              Inline: |
                New-AzSubscriptionDeployment -Location $(Location) -TemplateFile ".\main.bicep" -WhatIf
              workingDirectory: '$(System.DefaultWorkingDirectory)/modules/networking/'
              preferredAzurePowerShellVersion: 10.1.0

  - stage: 'NetworkLabDeploymentStackDeployment'
    dependsOn: 'NetworkLabWhatIf'
    displayName: Network Lab Deployment

    jobs:
      - deployment: 'NetworkLabDeployment'
        displayName: 'Network Lab Deployment Stack Deployment'
        pool:
          vmImage: 'windows-latest'
        environment: 'Bicep Lab'
        strategy:
          runOnce:
            deploy:
              steps:
                - checkout: self

                - task: replacetokens@5
                  inputs:
                    rootDirectory: '$(System.DefaultWorkingDirectory)/modules/networking/'
                    targetFiles: '**/*.bicepparam'
                    encoding: 'auto'
                    tokenPattern: 'default'
                    writeBOM: true
                    actionOnMissing: 'warn'
                    enableTelemetry: false

                - task: AzurePowerShell@5
                  displayName: 'Azure Powershell Network Lab Deployment Stack Deployment'
                  inputs:
                    azureSubscription: $(azureSubscription)
                    ScriptType: InlineScript
                    Inline: |
                      New-AzSubscriptionDeploymentStack -Name $(deploymentStackName) -Location $(Location) -TemplateFile ".\main.bicep" -TemplateParameterFile ".\main.bicepparam"
                    workingDirectory: '$(System.DefaultWorkingDirectory)/modules/networking/'
                    preferredAzurePowerShellVersion: 10.1.0

  - stage: 'NetworkLabDeploymentStackDeletion'
    dependsOn: 'NetworkLabDeploymentStackDeployment'
    displayName: Network Lab Deletion

    jobs:
      - deployment: 'NetworkLabDeployment'
        displayName: 'Network Lab Deployment Stack Deletion'
        pool:
          vmImage: 'windows-latest'
        environment: 'Bicep Lab'
        strategy:
          runOnce:
            deploy:
              steps:
                - checkout: self
                - task: AzurePowerShell@5
                  displayName: 'Azure Powershell Network Lab Deployment Stack Deployment'
                  inputs:
                    azureSubscription: $(azureSubscription)
                    ScriptType: InlineScript
                    Inline: |
                      Remove-AzSubscriptionDeploymentStack -Name $(deploymentStackName) -DeleteAll
                    workingDirectory: '$(System.DefaultWorkingDirectory)/modules/networking/'
                    preferredAzurePowerShellVersion: 10.1.0
